apiVersion: v2
appVersion: 1.1.0
dependencies:
- condition: nfd.enabled
  name: node-feature-discovery
  repository: ""
  version: 0.1.0
description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
home: https://github.com/NVIDIA/gpu-operator
kubeVersion: '>= 1.13.0-0'
name: gpu-operator
version: 1.1.0
